<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Make Payment</name>
   <tag></tag>
   <elementGuidId>f07c6252-06b6-4ad9-b0c0-ded4af5358cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;billing-proceed-button&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b50bf063-beb3-43f9-b76c-bcb78c612ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>billing-proceed-button</value>
      <webElementGuid>ec7d9a5b-687a-453e-bf33-c64d03507b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d5ece9f1-500e-49c2-8668-5f6f7963a29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-1orxvht ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-lg shadow-none   h-[49px] bg-surfaceAlertSuccesshighLight dark:bg-surfaceAlertSuccesshighDark false p-3 w-full !rounded</value>
      <webElementGuid>e86ffa76-ac2b-40eb-b64d-858eed85761c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Make Payment</value>
      <webElementGuid>1facf5b7-ad7e-497c-af0d-6538c0dc52ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tailwind-core&quot;)/body[@class=&quot;__className_a37cae layout_customScrollbar__E0DvH !w-full&quot;]/div[@class=&quot;css-1to9m9p ant-app&quot;]/main[@class=&quot;bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark min-h-full min-w-full&quot;]/section[@class=&quot;min-h-screen&quot;]/section[@class=&quot;w-full h-fit min-h-screen bg-surfaceBaseBg1Light dark:bg-surfaceBaseBg1Dark&quot;]/section[@class=&quot;container mt-10 px-4 xl:px-0 mb-4 lg:mb-0&quot;]/div[@class=&quot;grid grid-cols-12 gap-4&quot;]/div[@class=&quot;space-y-4 col-span-12 lg:col-span-3 mb-4&quot;]/div[1]/div[@class=&quot;flex flex-col gap-4 overflow-hidden border border-surfaceBaseBg2Light dark:border-surfaceBaseBg2Dark  rounded-lg bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark shadow-sm shadow-surfaceBaseBg1Light dark:shadow-surfaceBaseBg1Dark bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark billing-card-wrapper&quot;]/div[@class=&quot;px-3 pb-3 flex flex-col gap-2&quot;]/button[@class=&quot;ant-btn css-1orxvht ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-lg shadow-none   h-[49px] bg-surfaceAlertSuccesshighLight dark:bg-surfaceAlertSuccesshighDark false p-3 w-full !rounded&quot;]</value>
      <webElementGuid>4cd01f97-96d6-4776-a249-b38b7b9dcad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>ca64d75b-4c99-4ae9-908b-07cf345773d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div/main/section/section/section[2]/div/div[2]/div/div/div[2]/button</value>
      <webElementGuid>aba0fcb5-3e30-4541-8c95-dad72be506d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$39.00'])[3]/following::button[1]</value>
      <webElementGuid>89bc485c-8d4f-4319-a38b-c54dad3fef3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Amount'])[2]/following::button[1]</value>
      <webElementGuid>40e219d5-dfd1-4f52-aaf9-06d6e52ac71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::button[1]</value>
      <webElementGuid>0e3f7961-85fe-4bc6-b7ee-3ab791fabd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>c5a11fc3-4c17-4319-9515-e22e93aefac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Make Payment' or . = 'Make Payment')]</value>
      <webElementGuid>6fe97ba2-5a32-4ddd-9869-f4fc8e5c0a09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
