<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_emailOrPhoneField</name>
   <tag></tag>
   <elementGuidId>b938ea26-a7f9-4605-aa3d-696bccc366ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailOrPhoneField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailOrPhoneField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Enter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>132b5d90-5732-4551-9cd1-fd1c17fd2170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailOrPhoneField</value>
      <webElementGuid>a5e274b7-374c-4212-af2a-0452bc7306da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>effbdaad-e985-48d4-99ac-6d21814318ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>b3adfd0e-d98d-4728-88d8-f46ba6904129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input !p-3 leading-[22px] text-sm text-textBaseDarkLight dark:text-textBaseDarkDark font-bold bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark !font-normal placeholder:!text-xs placeholder:!font-normal text-textBaseDarkLight dark:text-textBaseDarkDark bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark placeholder-textBaseGraymediumLight dark:placeholder-textBaseGraymediumDark border border-borderBaseGreymediumLight dark:border-borderBaseGreymediumDark css-1wgm7nn ant-input-outlined</value>
      <webElementGuid>8b68b38e-16c5-4aed-867b-a6ab9d6e9ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>420c22b4-855f-4344-ae82-322f76dacdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailOrPhoneField&quot;)</value>
      <webElementGuid>61d5dc68-7232-4b0a-ba72-dd9a2b4eb450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailOrPhoneField']</value>
      <webElementGuid>d629183a-d15f-4715-9ae1-237c40bade16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div/main/section/section/section[2]/div/div/div[3]/div/div/div[2]/div/span/div/section/form/section/div[2]/section/span/span/input</value>
      <webElementGuid>3e50ceac-ab8f-433a-812c-add4e0197959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>1b1a3f4b-bf0f-411b-a8a8-aaaf93d0a7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emailOrPhoneField' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>9c071366-12ac-408e-9d47-96ac5c4e621a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
