<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your Email IDMobile Number_emai_a52cda</name>
   <tag></tag>
   <elementGuidId>f1b5353e-6314-43cb-a9b5-8fd60cef4055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailOrPhoneField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailOrPhoneField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Enter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>94997a55-b988-49ac-b40c-520e446d0f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailOrPhoneField</value>
      <webElementGuid>99efc292-e9ec-491f-ac0f-1e1d80d940c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>54554c51-bd30-4d70-88b1-ad784734de61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>d0ca19cc-688f-4972-8368-ec8a93eb0f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input !p-3 leading-[22px] text-sm text-textBaseDarkLight dark:text-textBaseDarkDark font-bold bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark css-zj9fva ant-input-outlined rounded-md placeholder:text-textBaseGraymediumLight dark:placeholder:text-textBaseGraymediumDark placeholder:font-normal bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark [&amp;_.ant-input-group-addon]:!overflow-hidden [&amp;_.ant-input-group-addon]:!bg-surfaceBaseWhiteLight [&amp;_.ant-input-group-addon]:dark:!bg-surfaceBaseWhiteDark disabled:bg-surfaceBaseGreylightLight dark:disabled:bg-surfaceBaseGreylightDark mt-2 h-12 !font-normal disabled:bg-transparent dark:disabled:bg-transparent [&amp;_.ant-input-group-addon]:px-2 [&amp;_.ant-input-group-addon]:py-2 [&amp;_.ant-input-disabled]:bg-surfaceBaseGreylightLight dark:[&amp;_.ant-input-disabled]:bg-surfaceBaseGreylightDark [&amp;_.ant-select-disabled]:bg-surfaceBaseGreylightLight dark:[&amp;_.ant-select-disabled]:bg-surfaceBaseGreylightDark [&amp;_.ant-input-group-wrapper-disabled&amp;_.ant-input-group-addon]:!bg-surfaceBaseGreylightLight dark:[.ant-input-group-wrapper-disabled&amp;_.ant-input-group-addon]:!bg-surfaceBaseGreylightDark</value>
      <webElementGuid>ee2dea59-9548-481a-8b7d-62b135712b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f69105bd-2ca7-4b3f-8775-00fd7c3141ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailOrPhoneField&quot;)</value>
      <webElementGuid>c773ae4a-c667-4693-9263-4e808ad09cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailOrPhoneField']</value>
      <webElementGuid>b8640e45-7a5c-4140-b9ea-77c368552cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div/main/section/section/form/section/input</value>
      <webElementGuid>cad23889-e677-4bcd-a085-95d5785a14e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3c5c3972-9f95-4c4c-a5f0-7c827a961e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'emailOrPhoneField' and @placeholder = 'Enter' and @type = 'text']</value>
      <webElementGuid>ef25167f-6927-422e-b124-093685f5e9ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
